# Generated by Django 6.1.1 on 2026-09-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalSystem', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalSystem.status'),
        ),
    ]
